### ISSUE TITLE
Icon-picker search picks up invalid icons

### ISSUE THREAD

**Issue by smurphos** [linuxmint/xapps#62]
Hi,

Using 1.4.1 icon-picker on 4.0.1 in Manjaro testing.

Manjaro for reasons unknown have a few different Manjaro logo icons sat in the root of /usr/share/icons/ outside of a specific icon theme. 

Using the icon picker to change the menu icon and searching by name returns these icons and allows them to be selected but they fail to apply. Following a Cinnamon restart the menu is without a icon. The icon does show as selected when the icon picker is reopened to try and fix the issue.

I think the search by name function needs to specifically exclude icons that are just sat in the root of /usr/share/icons/ as these icons do not appear to be technically in the system icon path.

Users can still successfully apply them via the file-system browse.

**Comment by collinss** [comment]
Are you getting any errors in the logs? I doubt this is an issue with the icon chooser as it's using the same mechanism to list the icon names as the menu applet uses to display them (gtk icon theme). If the icon is picked up by Gtk, it should also be able to show in the menu applet.

**Comment by mtwebster** [comment]
I'm not sure why the icon picker is displaying this icon, as it's not in a valid spot.  the 'hicolor' folder is the place for these sort of package-specific icons.  If I move manjaro-shiny.png to hicolor/64x64/apps and regenerate the icon cache (`sudo gtk-update-icon-cache /usr/share/icons/hicolor`) then it works.

I'm wondering if this icon is falling thru the cracks of gtk's icon fallback handling somehow, and is being picked up by the code that the icon chooser uses to sift thru icons, but not by icon name users.  I can reproduce this same issue using xapp's `xapp-gtk-window` test script (so the problem is not cinnamon-specific either)

For a bit of additional info what I'm talking about: https://developer.gnome.org/gtk3/stable/GtkIconTheme.html#gtk-icon-theme-set-search-path

**Comment by smurphos** [comment]
Cheers that makes sense, it's seems that the icon picker and the menu config GUI are using the fallback search to find the icon successfully, but Cinnamon isn't using the fallback search to actually display it on the panel.
